nginx:
    build: ./docker/nginx/
    ports:
        - 80:80
    links:
        - php
    volumes:
        - ./:/var/www/html
        - ./docker/nginx/conf.d:/etc/nginx/conf.d/

php:
    image: phalconphp/php-fpm:7-min
    volumes:
        - ./:/var/www/html
